/* eslint-disable */
// ============================================================
// AUTO-GENERATED by tools/generate-component-library.mjs
// Do NOT edit by hand — it is rewritten on every npm start/build
// and whenever shared/components changes while npm start runs.
// One entry per component folder under src/app/shared/components.
// Optional previews (sample inputs, example, overlay) belong in
// component-previews.ts, keyed by the entry id.
// ============================================================
import { Type } from '@angular/core';

import { AccordionComponent as Cmp0 } from '../../shared/components/accordion/accordion.component';
import { ActivityChartComponent as Cmp1 } from '../../shared/components/activity-chart/activity-chart.component';
import { AlertComponent as Cmp2 } from '../../shared/components/alert/alert.component';
import { AutocompleteSearchComponent as Cmp3 } from '../../shared/components/autocomplete-search/autocomplete-search.component';
import { AvatarComponent as Cmp4 } from '../../shared/components/avatar/avatar.component';
import { BadgeComponent as Cmp5 } from '../../shared/components/badge/badge.component';
import { ButtonComponent as Cmp6 } from '../../shared/components/button/button.component';
import { CheckboxGroupComponent as Cmp7 } from '../../shared/components/checkbox-group/checkbox-group.component';
import { DataTableComponent as Cmp8 } from '../../shared/components/data-table/data-table.component';
import { DrawerComponent as Cmp9 } from '../../shared/components/drawer/drawer.component';
import { DropdownComponent as Cmp10 } from '../../shared/components/dropdown/dropdown.component';
import { FancySpinnerComponent as Cmp11 } from '../../shared/components/fancy-spinner/fancy-spinner.component';
import { FileUploaderComponent as Cmp12 } from '../../shared/components/file-uploader/file-uploader.component';
import { FlagIconComponent as Cmp13 } from '../../shared/components/flag-icon/flag-icon.component';
import { FundingBarComponent as Cmp14 } from '../../shared/components/funding-bar/funding-bar.component';
import { IconComponent as Cmp15 } from '../../shared/components/icon/icon.component';
import { InfoTooltipComponent as Cmp16 } from '../../shared/components/info-tooltip/info-tooltip.component';
import { InputComponent as Cmp17 } from '../../shared/components/input/input.component';
import { LimitsCardComponent as Cmp18 } from '../../shared/components/limits-card/limits-card.component';
import { ModalComponent as Cmp19 } from '../../shared/components/modal/modal.component';
import { OtpInputComponent as Cmp20 } from '../../shared/components/otp-input/otp-input.component';
import { PageHeaderComponent as Cmp21 } from '../../shared/components/page-header/page-header.component';
import { ProfileAvatarComponent as Cmp22 } from '../../shared/components/profile-avatar/profile-avatar.component';
import { RadioGroupComponent as Cmp23 } from '../../shared/components/radio-group/radio-group.component';
import { RecentActivityComponent as Cmp24 } from '../../shared/components/recent-activity/recent-activity.component';
import { SearchInputComponent as Cmp25 } from '../../shared/components/search-input/search-input.component';
import { SectionCardComponent as Cmp26 } from '../../shared/components/section-card/section-card.component';
import { SegmentedTabsComponent as Cmp27 } from '../../shared/components/segmented-tabs/segmented-tabs.component';
import { StatusPopoverComponent as Cmp28 } from '../../shared/components/status-popover/status-popover.component';
import { StepperComponent as Cmp29 } from '../../shared/components/stepper/stepper.component';
import { TagPickerComponent as Cmp30 } from '../../shared/components/tag-picker/tag-picker.component';
import { TextareaComponent as Cmp31 } from '../../shared/components/textarea/textarea.component';
import { ToggleSwitchComponent as Cmp32 } from '../../shared/components/toggle-switch/toggle-switch.component';
import { WalletBalanceCardComponent as Cmp33 } from '../../shared/components/wallet-balance-card/wallet-balance-card.component';
import { WalletSelectorComponent as Cmp34 } from '../../shared/components/wallet-selector/wallet-selector.component';

export interface GeneratedLibraryEntry {
  /** Slug of the folder name under shared/components — also the detail-page URL id. */
  id: string;
  component: Type<unknown>;
  /** JSDoc text extracted from the component source. */
  description: string;
  /** True when the component declares required inputs — a live preview
   *  then needs sampleInputs in component-previews.ts. */
  requiredInputs: boolean;
}

export const GENERATED_COMPONENT_LIBRARY: GeneratedLibraryEntry[] = [
  { id: 'accordion', component: Cmp0, description: "Shared accordion component.", requiredInputs: false },
  { id: 'activity-chart', component: Cmp1, description: "Credits vs debits chart, drawn with plain SVG — no chart library. Bar and line modes share the same scale; the toggle chips drive `chartKind` / `chartRange` signals in the wallet store.", requiredInputs: false },
  { id: 'alert', component: Cmp2, description: "Shared alert component.", requiredInputs: false },
  { id: 'autocomplete-search', component: Cmp3, description: "Shared autocomplete search component.", requiredInputs: false },
  { id: 'avatar', component: Cmp4, description: "Gradient initials avatar (deterministic hue from the name).", requiredInputs: true },
  { id: 'badge', component: Cmp5, description: "Shared badge component.", requiredInputs: false },
  { id: 'button', component: Cmp6, description: "Shared button component.", requiredInputs: false },
  { id: 'checkbox-group', component: Cmp7, description: "Shared checkbox group component.", requiredInputs: true },
  { id: 'data-table', component: Cmp8, description: "Reusable table shared across pages (Organization entities, users, …). - Columns are configured via the `columns` input. - Cell markup is customised per column with `ng-template appTableCell=\"key\"`; columns without a template render the row property named by the key. - Providing an `ng-template appTableExpanded` makes rows expandable (accordion — one open at a time) with a chevron toggle per row. - `showRowMenu` renders a ⋮ button that emits `rowMenu`.", requiredInputs: true },
  { id: 'drawer', component: Cmp9, description: "Right-hand slide-over shell used by the Drafts and Approvals drawers. Content is projected; the shell owns the backdrop, panel animation, header and close affordances (backdrop click, X button, Escape).", requiredInputs: true },
  { id: 'dropdown', component: Cmp10, description: "Shared dropdown component.", requiredInputs: true },
  { id: 'fancy-spinner', component: Cmp11, description: "Shared fancy spinner component.", requiredInputs: false },
  { id: 'file-uploader', component: Cmp12, description: "Shared file uploader component.", requiredInputs: false },
  { id: 'flag-icon', component: Cmp13, description: "Circular country-flag image (20×20 by default, object-fit: cover). Falls back to the emoji flag when the image cannot load (offline).", requiredInputs: true },
  { id: 'funding-bar', component: Cmp14, description: "Image 10 — the lavender funding strip: bank account selector, funding method selector, maskable account number and routing.", requiredInputs: false },
  { id: 'icon', component: Cmp15, description: "Tabler Icons (webfont) wrapper. Renders `<i class=\"ti ti-...\">` so every icon in the app is a genuine Tabler icon and inherits `currentColor`. Legacy internal names are mapped to Tabler classes.", requiredInputs: true },
  { id: 'info-tooltip', component: Cmp16, description: "Shared info tooltip component.", requiredInputs: true },
  { id: 'input', component: Cmp17, description: "Shared input component.", requiredInputs: false },
  { id: 'limits-card', component: Cmp18, description: "Shared limits card component.", requiredInputs: false },
  { id: 'modal', component: Cmp19, description: "Shared modal component.", requiredInputs: false },
  { id: 'otp-input', component: Cmp20, description: "Shared otp input component.", requiredInputs: false },
  { id: 'page-header', component: Cmp21, description: "Shared page header component.", requiredInputs: true },
  { id: 'profile-avatar', component: Cmp22, description: "The signed-in user's avatar (generated style or uploaded photo) from AccountStateService, at any size; optionally shows an edit (pencil) badge that emits when clicked. Used in the header profile chip and on the Account page.", requiredInputs: false },
  { id: 'radio-group', component: Cmp23, description: "Shared radio group component.", requiredInputs: true },
  { id: 'recent-activity', component: Cmp24, description: "\"Recent activity\" list next to the balance card.", requiredInputs: false },
  { id: 'search-input', component: Cmp25, description: "Shared search input component.", requiredInputs: false },
  { id: 'section-card', component: Cmp26, description: "Shared section card component.", requiredInputs: false },
  { id: 'segmented-tabs', component: Cmp27, description: "Shared segmented tabs component.", requiredInputs: true },
  { id: 'status-popover', component: Cmp28, description: "\"Company status\" popover on the Status badge — opens on hover or click and lists identity level, payment approvals and connected services with their current state.", requiredInputs: false },
  { id: 'stepper', component: Cmp29, description: "Shared stepper component.", requiredInputs: true },
  { id: 'tag-picker', component: Cmp30, description: "Shared tag picker component.", requiredInputs: false },
  { id: 'textarea', component: Cmp31, description: "Shared textarea component.", requiredInputs: false },
  { id: 'toggle-switch', component: Cmp32, description: "iOS-style toggle used by \"Show only drafts created by me\".", requiredInputs: false },
  { id: 'wallet-balance-card', component: Cmp33, description: "The gradient \"Wallet Balance\" hero card. The wireframe globe fills the card background and rotates each time a different wallet is selected; the Wallet Details drawer opens from the wallet dropdown.", requiredInputs: false },
  { id: 'wallet-selector', component: Cmp34, description: "Image 9 — the currency dropdown inside the Wallet Balance card. Switching a wallet re-queries activity + transactions via the store.", requiredInputs: false },
];
