# app-customer-web-PR-pipelines

trigger: none
        
pr: none

pool:
  vmImage: windows-latest


variables:
 nodeVersion: '22.22.3'
 workingDirectory: '$(System.DefaultWorkingDirectory)'
#  buildOutputDirectory: '$(System.DefaultWorkingDirectory)\dist\xtrm-dashboard'
 buildOutputDirectory: '$(System.DefaultWorkingDirectory)/dist/xtrm-dashboard/browser'
 artifactName: 'drop'

stages:

- stage: Build
  displayName: 'Build Customer Web'

  jobs:

  - job: BuildCustomerWeb
    displayName: 'Build and Validate Customer Web'
    timeoutInMinutes: 30
    steps:
      
     
    - checkout: self
      # clean: true
      displayName: 'Checkout Source Code'

    - task: UseNode@1
      displayName: 'Install Node.js'
      inputs:
        version: '$(nodeVersion)'


    - script: |
        npm ci
      displayName: 'Install npm Dependencies'
      workingDirectory: '$(workingDirectory)'

    - task: SnykSecurityScan@1
      displayName: 'Snyk Application Scan'
      inputs:
        serviceConnectionEndpoint: 'uc9-synk-sc-accesstoken-UC10'
        testType: 'app'
        monitorWhen: 'never'
        failOnIssues: false
        organization: 'xtrm-inc.-default'
        failOnThreshold: 'high'


    - task: SnykSecurityScan@1
      displayName: 'Snyk Code Scan'
      inputs:
        serviceConnectionEndpoint: 'uc9-synk-sc-accesstoken-UC10'
        testType: 'code'
        monitorWhen: 'always'
        failOnIssues: true
        organization: 'xtrm-inc.-default'
        failOnThreshold: 'high'


    - task: Npm@1
      displayName: 'Build Customer Web'
      inputs:
        command: 'custom'
        workingDir: '$(workingDirectory)'
        customCommand: 'run build'

        

    